import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useImages } from "@/hooks/useImages";
import { useEffect } from "react";

export default function Home() {
  const { images, isLoading } = useImages(1, 10);

  useEffect(() => {
    console.log(images);
  }, [images])

  useEffect(() => {
    console.log(isLoading);
  }, [isLoading])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
      </main>
    </>
  );
}
